version = 1

# Software and configurations
[[annotations]]
path = [
    "web/**",
    "tests/**", 
    "scripts/**", 
    ".github/**",
    "package.json",
    "package-lock.json",
    "config.json",
    "REUSE.toml",
    ".gitignore",
    ".mailmap"
]
SPDX-FileCopyrightText = "2025 TechRadar Curators and Organisations, including curators in CITATION.cff, https://everse.software/about/consortium/"
SPDX-License-Identifier = "MIT"
SPDX-Year = "2025"
SPDX-FileType = "Software"

# TechRadar content (Data, Documentation and assets)
[[annotations]]
path = [
    "data/**",
    "web/public/**",
    "CONTRIBUTING.md",
    "README.md",
    "about.md",
    "CITATION.cff",
    "radar/**"
]
SPDX-FileCopyrightText = "2025 TechRadar Curators and Organisations, including curators in CITATION.cff, https://everse.software/about/consortium/"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"
SPDX-Year = "2025"
SPDX-FileType = "Documentation"