name: Check Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write # required for peter-evans/create-issue-from-file
    steps:
      - uses: actions/checkout@v5

      - name: Link Checker (CI strict)
        if: github.event_name != 'schedule'
        id: lychee_strict
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --root-dir ${{ github.workspace }} 'web/**/*.jsx' 'web/**/*.html' './**/*.md' './quality-tools/**/*.json'
          fail: true

      - name: Link Checker (scheduled report)
        if: github.event_name == 'schedule'
        id: lychee_schedule
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --root-dir ${{ github.workspace }} 'web/**/*.jsx' 'web/**/*.html' './**/*.md' './quality-tools/**/*.json'
          fail: false

      - name: Create Issue From File
        if: github.event_name == 'schedule' && steps.lychee_schedule.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
