name: Prettier Formatting Check & Fix

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            .node_modules
          key: ${{ runner.os }}-techradar-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Check tools jsonld formatting with Prettier
        id: check_format
        run: |
          npm run lint-prettier:check
        continue-on-error: true  # Allows the workflow to continue even if this step fails

      - name: Fix code formatting with Prettier
        if: steps.check_format.outcome == 'failure'  # Run only if check_format failed
        run: |
          npm run lint-prettier:fix
        
      - name: Commit changes if Prettier fixed formatting
        if: steps.check_format.outcome == 'failure'  # Run only if check_format failed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "fix: apply Prettier formatting" || echo "No changes to commit"
          git push
