name: Lint JSON-LD and Python Script

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install jsonld-lint and prettier
        run: npm install -g jsonld-lint 

      - name: Run JSON-LD lint checks
        run: |
          find ./data/software-tools -name "*.jsonld" -print0 | xargs -0 -n1 jsonld-lint

      # - name: Set up Python 3.12
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.12"

      # - name: Install Python dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install pylint

      # - name: Run Python lint checks
      #   run: |
      #     pylint ../scripts/*.py
